const tooltipDescs = {
    tokenAcctUrl: "The URL of the token account, where an account's balances and transactions are organized for a particular token",
    tokenUrl: "The URL of the token",
    acctUrl: "The URL of the account",
    token: "The name and symbol of the token",
    balance: "The total number of tokens for this account",
    creditBalance: "The total number of credits for this account. Credits are non-transferable tokens used in the Accumulate network to fund ADI-create transactions and pay for data storage",
    creditsAdded: "Number of credits added",
    tokenSymbol: "Abbreviation used to easily identify the token within Accumulate",
    tokenPrecision: "The minimum divisible unit of this token (i.e. how many digits after the decimal point)",
    txType: "Transaction type",
    txFrom: "The sending party of this transaction",
    txTo: "The receiving party, or parties, of this transaction",
    txId: "The unique identifier assigned to this transaction",
    txCause: "The cause of the Accumulate transaction",
    txStatus: "The status of the Accumulate transaction",
    adiUrl: "The URL of the ADI (Accumulate Digital Identifier)",
    identityUrl: "The URL of the Light Identity",
    adiDirectory: "a way of organizing accounts within an ADI",
    pubKey: "The Public Key of the ADI",
    amount: "The number of tokens transferred",
    keyBookUrl: "The Url of the keybook (store the Hierarchical Key Management Structure of an ADI using Key Pages and Keys within those pages.) ",
    keyBook: "store the Hierarchical Key Management Structure of an ADI using Key Pages and Keys within those pages.",
    keyPageUrl: "The URL of the Keypage (defines the set of Keys required to validate a transaction)",
    keyData: "defines the set of Keys required to validate a transaction",
    keyType: "The type of Key defined as the hash of the public key for a signature",
    nonce: "number added to a hashed or encrypted—block in a blockchain",
    sponsor: "The URL of the principal",
    recipient: "the account that is receiving a transaction",
    threshold: "the required m of n to execute a transaction",
    maxSupply: "The maximum number of ACME coded to exist in the lifetime of the cryptocurrency.",
    totalSupply: "The amount of ACME that have already been created.",
    circSupply: "The amount of ACME that are circulating in the market, calculated as total supply minus ACME owned by the Accumulate Foundation."
};

export default tooltipDescs;
