const tooltipDescs = {
    tokenAcctUrl: "The URL of the token account, where an account's balances and transactions are organized for a particular token",
    tokenUrl: "The URL of the token",
    token: "The name and symbol of the token",
    balance: "The total number of tokens for this account",
    creditBalance: "The total number of credits for this account. Credits are non-transferable tokens used in the Accumulate network to fund ADI-create transactions and pay for data storage",
    creditsAdded: "Number of credits added",
    tokenSymbol: "Abbreviation used to easily identify the token within Accumulate",
    tokenPrecision: "The minimum divisible unit of this token (i.e. how many digits after the decimal point)",
    txType: "Transaction type",
    txFrom: "The sending party of this transaction",
    txTo: "The receiving party, or parties, of this transaction",
    txId: "The unique identifier assigned to this transaction",
    txCause: "The cause of the Accumulate transaction",
    txStatus: "The status of the Accumulate transaction",
    adiUrl: "The URL of the ADI (Accumulate Digital Identifier)",
    adiDirectory: "",
    pubKey: "The Public Key of the ADI",
    amount: "The number of tokens transferred",
    keyBookUrl: "",
    keyBook: "",
    keyPageUrl: "",
    keyData: "",
    keyType: "",
    nonce: "",
    sponsor: "",
    recipient: "",
    threshold: "",
    scratchAccountDeletionWarning: "Protocol only preserves the last 2 weeks of entries within this account.",
};

export default tooltipDescs;